# Generated by Django 5.1.4 on 2025-01-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="Category of the item (e.g., Appetizers, Drinks).",
                max_length=100,
            ),
        ),
    ]
